/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { CallRecordService } from "../callRecord.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CallRecordCreateInput } from "./CallRecordCreateInput";
import { CallRecord } from "./CallRecord";
import { CallRecordFindManyArgs } from "./CallRecordFindManyArgs";
import { CallRecordWhereUniqueInput } from "./CallRecordWhereUniqueInput";
import { CallRecordUpdateInput } from "./CallRecordUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CallRecordControllerBase {
  constructor(
    protected readonly service: CallRecordService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CallRecord })
  @nestAccessControl.UseRoles({
    resource: "CallRecord",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createCallRecord(
    @common.Body() data: CallRecordCreateInput
  ): Promise<CallRecord> {
    return await this.service.createCallRecord({
      data: {
        ...data,

        customer: data.customer
          ? {
              connect: data.customer,
            }
          : undefined,
      },
      select: {
        callDuration: true,
        callTimestamp: true,
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        id: true,
        recordingUrl: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [CallRecord] })
  @ApiNestedQuery(CallRecordFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "CallRecord",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async callRecords(@common.Req() request: Request): Promise<CallRecord[]> {
    const args = plainToClass(CallRecordFindManyArgs, request.query);
    return this.service.callRecords({
      ...args,
      select: {
        callDuration: true,
        callTimestamp: true,
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        id: true,
        recordingUrl: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CallRecord })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CallRecord",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async callRecord(
    @common.Param() params: CallRecordWhereUniqueInput
  ): Promise<CallRecord | null> {
    const result = await this.service.callRecord({
      where: params,
      select: {
        callDuration: true,
        callTimestamp: true,
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        id: true,
        recordingUrl: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CallRecord })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CallRecord",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateCallRecord(
    @common.Param() params: CallRecordWhereUniqueInput,
    @common.Body() data: CallRecordUpdateInput
  ): Promise<CallRecord | null> {
    try {
      return await this.service.updateCallRecord({
        where: params,
        data: {
          ...data,

          customer: data.customer
            ? {
                connect: data.customer,
              }
            : undefined,
        },
        select: {
          callDuration: true,
          callTimestamp: true,
          createdAt: true,

          customer: {
            select: {
              id: true,
            },
          },

          id: true,
          recordingUrl: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CallRecord })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CallRecord",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteCallRecord(
    @common.Param() params: CallRecordWhereUniqueInput
  ): Promise<CallRecord | null> {
    try {
      return await this.service.deleteCallRecord({
        where: params,
        select: {
          callDuration: true,
          callTimestamp: true,
          createdAt: true,

          customer: {
            select: {
              id: true,
            },
          },

          id: true,
          recordingUrl: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
